modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Lykrast/HarvestersNight/issues"

[[mods]]
modId="harvestersnight"
version="${version}"
displayName="Harvester's Night"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harvesters-night"
credits="Team Fortress 2 for the Merasmus sounds, Thermal Foundation for the Sickle code"
authors="Lykrast"
description='''
Entry for MMD Spooky Jam 2018. Fight the Harvester when its night comes.
'''

[[dependencies.harvestersnight]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.harvestersnight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"